### ISSUE TITLE
quicrq_media_close - expose reason for the close

### ISSUE THREAD

**Issue by suhasHere** [Quicr/quicrq#77]
It will be handy for the application too know why a given consumer context was closed.

**Comment by TimEvens** [comment]
@suhasHere, shouldn't this be part of the protocol?  Does the spec define the close ENUM/values?  We'll need this from the relays as well as client side (both subscriber and producers).  For example:

1. relay closes named stream due to producer (which could include multiple producers) lack of inactivity
2. subscriber unsubscribes
3. subscriber timeouts. This may be based on retries to send data to subscriber
4. etc.

**Comment by huitema** [comment]
The interface is defined currently as:
```
typedef enum {
    quicrq_media_datagram_ready = 0,
    quicrq_media_start_point,
    quicrq_media_final_object_id,
    quicrq_media_real_time_cache,
    quicrq_media_close
} quicrq_media_consumer_enum;

typedef struct st_quicrq_object_stream_consumer_properties_t {
    uint8_t flags;
} quicrq_object_stream_consumer_properties_t;

typedef int (*quicrq_object_stream_consumer_fn)(
    quicrq_media_consumer_enum action,
    void* object_consumer_ctx,
    uint64_t current_time,
    uint64_t group_id,
    uint64_t object_id,
    const uint8_t* data,
    size_t data_length,
    quicrq_object_stream_consumer_properties_t* properties);
```

The interface function works well for the "media" actions, for which the group id, object ID and time parameters are sufficient. The simplest way to solve this issue would be to add an error code parameter, with zero defined as "no error". But that is an incompatible change. @suhasHere, is that OK?

**Comment by huitema** [comment]
The current conditions are:

* end of media signaled by provider
* application calls `quicrq_unsubscribe_object_stream`
* connection to the relay is closed

In the latter case, we have of course a next question, "why was the connection closed"?

* because the application is ending and closed the quicrq context, which closes all connections
* because the application decided to close the connection
* because the underlying QUIC connection was closed by the remote application, in which case we have an application specific error code and possibly a diagnostic message
* because the underlying QUIC connection was closed by the QUIC layer, in which case we have a QUIC error code and possibly a diagnostic message

Do we want to expose all that?

**Comment by suhasHere** [comment]
Thanks @huitema  .. these look fine to me as well. 
For the connection to relay is closed case, how about we expose
- remote close 
- closed by the QUIC Layer 

these 2 will be useful for diagnosis 


Also your proposal for API change is fine
