### ISSUE TITLE
quicrq_t.exe fails to run on windows with error on libcrypto-3.dll not found

### ISSUE THREAD

**Issue by hd51515** [Quicr/quicrq#92]
"Reinstalling the program may fix the problem"

This seems to be happening after support for openssl3 was added in picoquic

**Comment by huitema** [comment]
That "not found" message means that OpenSSL3 was not properly installed, and that libcrypto-3.dll was not on the search path for shared DLL. You should either update that path or manually copy the DLL to the run time directory.

**Comment by huitema** [comment]
For a DLL to be accessible by programs, it needs to be "registered". This typically happens when the library is installed. There would be a ".lib" file linked with the program and including a call to "load example.dll" -- in our case, one of the opensslv3 library is doing that call. If the library is registered, the "load" succeeds. Otherwise, it only succeeds if the dll file is present in the local directory.

Obviously, "libcrypto-3.dll" was not registered when openssl3 was installed. You can still do it, as explained for example in: https://answers.microsoft.com/en-us/windows/forum/all/how-do-i-register-dll-files-in-a-windows-10-64-bit/27429279-61ff-463b-bb77-3f30be2954ba.

**Comment by hd51515** [comment]
I had to manually copy libcrypto-3.dll to quicrq\debug in my setup. Not sure why it wasn't picked up even though it included in the path.
